# This is a basic workflow that is manually triggered

name: Bump version

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: "Semver type of new version (major / minor / patch)"
        # Input has to be provided for the workflow to run
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "bump-version"
  bump-version:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Check out the content (source branch).  Use a deploy key so that
      # when we push changes, it will trigger the release workflow
      # run that runs on: tag. (Using the GitHub token would
      # not run the workflow to prevent infinite recursion.)
      - name: Check out source
        uses: actions/checkout@v2

      # - name: Setup Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: "16.13.0"

      # - name: Install npm packages
      #   run: yarn install

      - name: Setup Git
        run: |
          git config user.name 'Dxdao Governance Team'
          git config user.email 'dxdaoGovernanceTeam@gmail.com'

      - name: bump version
        id: package-version
        run: npm version ${{ github.event.inputs.version }} | read message | echo "NEXT_PACKAGE_VERSION=$message" >> $GITHUB_OUTPUT

      - name: log new version
        run: echo "Updated to version ${{ steps.package-version.outputs.NEXT_PACKAGE_VERSION  }}"

      - name: Push latest version & new tag
        run: git push origin main --follow-tags

  publish-to-npm:
    name: Publish to npm
    runs-on: ubuntu-latest
    needs: bump-version
    permissions:
      id-token: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16.13.0"
          registry-url: "https://registry.npmjs.org"

      - name: Install latest npm version
        run: npm install -g npm@latest

      - name: Install dependencies and build
        run: yarn install && yarn compile

      - name: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: publish-to-npm
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release
        run: gh release create ${{ github.ref }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

